import {
  faWifi,
  faCoffee,
  faCar,
  faBolt,
  faShield,
  faPrint,
  faVideo,
  faUsers,
  faBuilding,
  faSnowflake,
  faBell,
  faKey,
  faTv,
  faUtensils,
  faSoap,
  faDumbbell,
  faBicycle,
  faBaby,
  faPaw,
  faShower,
  faBed,
  faCouch,
  faFan,
  faLightbulb,
  faWheelchair,
  faTree,
  faWater,
  faBroom,
  faEnvelope,
  faPlug,
  faPhone,
  faDesktop,
  faCircleQuestion
} from '@fortawesome/free-solid-svg-icons';

export const ICON_MAP = {
  wifi: faWifi,
  coffee: faCoffee,
  parking: faCar,
  power_backup: faBolt,
  security: faShield,
  printer: faPrint,
  projector: faVideo,
  meeting: faUsers,
  community: faUsers,
  building: faBuilding,
  air_conditioning: faSnowflake,
  reception: faBell,
  locker: faKey,
  tv: faTv,
  kitchen: faUtensils,
  laundry: faSoap,
  gym: faDumbbell,
  bicycle: faBicycle,
  childcare: faBaby,
  pet: faPaw,
  shower: faShower,
  beds: faBed,
  lounge: faCouch,
  fridge: faSnowflake,
  microwave: faUtensils,
  fan: faFan,
  lighting: faLightbulb,
  access: faKey,
  cctv: faVideo,
  wheelchair: faWheelchair,
  outdoor: faTree,
  pool: faWater,
  housekeeping: faBroom,
  mail_handling: faEnvelope,
  generator: faPlug,
  intercom: faPhone,
  workstation: faDesktop,
};

export const ICON_FALLBACK = faCircleQuestion;

export const ICON_OPTIONS = [
  { label: 'WiFi', value: 'wifi' },
  { label: 'Coffee', value: 'coffee' },
  { label: 'Parking', value: 'parking' },
  { label: 'Power Backup', value: 'power_backup' },
  { label: 'Security', value: 'security' },
  { label: 'Printer', value: 'printer' },
  { label: 'Projector', value: 'projector' },
  { label: 'Meeting Room', value: 'meeting' },
  { label: 'Community', value: 'community' },
  { label: 'Building', value: 'building' },
  { label: 'AC / Air Conditioning', value: 'air_conditioning' },
  { label: 'Reception', value: 'reception' },
  { label: 'Locker / Storage', value: 'locker' },
  { label: 'TV', value: 'tv' },
  { label: 'Kitchen / Pantry', value: 'kitchen' },
  { label: 'Laundry', value: 'laundry' },
  { label: 'Gym / Fitness', value: 'gym' },
  { label: 'Bicycle Parking', value: 'bicycle' },
  { label: 'Childcare', value: 'childcare' },
  { label: 'Pet Friendly', value: 'pet' },
  { label: 'Bathroom / Shower', value: 'shower' },
  { label: 'Beds', value: 'beds' },
  { label: 'Lounge', value: 'lounge' },
  { label: 'Fridge', value: 'fridge' },
  { label: 'Microwave', value: 'microwave' },
  { label: 'Fan', value: 'fan' },
  { label: 'Lighting', value: 'lighting' },
  { label: 'Key / Access', value: 'access' },
  { label: 'CCTV', value: 'cctv' },
  { label: 'Wheelchair Access', value: 'wheelchair' },
  { label: 'Outdoor / Garden', value: 'outdoor' },
  { label: 'Pool / Swimming', value: 'pool' },
  { label: 'Housekeeping', value: 'housekeeping' },
  { label: 'Mail Handling', value: 'mail_handling' },
  { label: 'Generator', value: 'generator' },
  { label: 'Intercom', value: 'intercom' },
  { label: 'Workstation / Desk', value: 'workstation' },
];
